### ISSUE TITLE
Add a LoopMode or something like that

### ISSUE THREAD

**Issue by modulovalue** [Norbert515/flutter_sequence_animation#3]
There are a ton of use-cases for having a looping animation.

My suggestion for the API would be to add a `LoopMode` to `addAnimatable` e.g. LoopMode.dontRepeat, LoopMode.pingPong, LoopMode.restart

Do you think this could be achieved with a reasonable amount of effort? @Norbert515

**Comment by Norbert515** [comment]
Looping is indeed something that should be easier to do. But I think it should rather be in the `AnimationController` itself because there are tons of use cases for looping besides the sequence animation and having different APIs for different use cases isn't very nice. I'd suggest doing a PR for the `AnimationController`.
